name: openscope-differentiation
channels:
  - conda-forge
  - defaults
dependencies:
  - pyarrow=3.0.0
  - matplotlib=3.3.4
  - ipywidgets=7.6.3
  - r-multcomp=1.4_10
  - colorcet=2.0.6
  - h5py=2.10.0
  - numpy=1.20.1
  - r-broom=0.5.2
  - jupyterlab=3.0.14
  - scipy=1.6.2
  - r=3.6.0
  - umap-learn=0.5.1
  - hdf5=1.10.6
  - python=3.8.8
  - r-emmeans=1.3.4
  - rpy2=3.4.4
  - pyyaml=5.4.1
  - r-lme4=1.1_21
  - joblib=1.0.1
  - scikit-learn=0.24.1
  - seaborn=0.11.1
  - r-tidyverse=1.2.1
  - pandas=1.2.4
  - tqdm=4.59.0
