a: null
angular_rp_forest: false
b: null
force_approximation_algorithm: false
init: spectral
learning_rate: 1.0
local_connectivity: 1.0
low_memory: false
metric: euclidean
metric_kwds: null
min_dist: 0.5
n_components: 8
n_epochs: null
n_neighbors: 50
negative_sample_rate: 5
output_metric: euclidean
output_metric_kwds: null
random_state: 42
repulsion_strength: 1.0
set_op_mix_ratio: 1.0
spread: 1.0
target_metric: categorical
target_metric_kwds: null
target_n_neighbors: -1
target_weight: 0.5
transform_queue_size: 4.0
transform_seed: 42
unique: false
verbose: false
